### ISSUE TITLE
Should not throw on missing modules

### ISSUE THREAD

**Issue by mastilver** [mastilver/modules-cdn-webpack-plugin#1]
It should just log a warning instead

**Comment by van-nguyen** [comment]
Just the plugin I was looking for, I'm surprised it does not exist anywhere else yet. Nice work so far 👍 

When a module is not found I'm getting this:
``` js
throw new Error(`'${moduleName}' is not available through cdn, add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json if you think it should`);
```

Would it be possible to add an option which can be additional to the `modules.json` file, rather than needing to do a pull request every time it doesn't find it.

i.e.
``` js
new ModulesCdnWebpackPlugin({
  modules: ['vue'],
  extra: {
    "vue": {
      "var": "Vue",
      "url": "https://unpkg.com/vue@[version]/dist/vue.runtime.min.js"
    }
  }
})
```

This would make it much more flexible and less opinionated, what are your thoughts?

Cheers.
