### ISSUE TITLE
Option for URLs for certain package

### ISSUE THREAD

**Issue by Ciantic** [mastilver/modules-cdn-webpack-plugin#14]
I have mobx, react, react-dom dependencies, this module generates script tags only for react and react-dom and not for the mobx.

However I know that mobx has unpkg url, how can I say this to the modules cdn plugin?

Since I know mobx has this working url: https://unpkg.com/mobx@3.1.4/lib/mobx.umd.min.js I would like to define this in the plugin, e.g:
```javascript
new ModulesCdnWebpackPlugin({
  urls: { // This is made up property
    "mobx" : "https://unpkg.com/mobx@VERSION/lib/mobx.umd.min.js"
  }
})
```

Also I think I would like to use minified version of react so I could use this url instead:

https://unpkg.com/react@15.6.1/dist/react.min.js

I could define that also in the new urls property.

**Comment by mastilver** [comment]
Please send me a PR to https://github.com/mastilver/module-to-cdn to add `mobx`

To get the minified version set NODE_ENV to `production` (see https://github.com/mastilver/modules-cdn-webpack-plugin#optionsenv)

**Comment by mastilver** [comment]
@Ciantic I just added `mobx`: https://github.com/mastilver/module-to-cdn/commit/91994271b26fbcaac6d9099eb8f267dbc563814c#diff-59b1a68f15f8ddcc853ff5d69cae5f41R147

**Comment by Ciantic** [comment]
@mastilver there is also a standard which you could use:

> @Ciantic it would seem like that webpack plugin does not support the unpkg key in package.json, which we define for each of our packages and rely on for correct usage with unpkg.com (see https://unpkg.com/#query-parameters). not much to be done on this end 😭

This is direct quote from here: https://github.com/palantir/blueprint/issues/303

So you shouldn't add a exception to your package, just check that unpkg key in package.json I think.

**Comment by mastilver** [comment]
@Ciantic There is multiple reasons why I'm not following that

Taking the `blueprint` package, if I was following the `unpkg` key, and the user asked for a `production` url, there would me not way to tell which is the production url, so I would probably just add `.min` to the normal url (which wouldn't work with `blueprint` because it doesn't have one)
And what if, some package decided to use `unpkg` key for there production build?

There is so many parameters! So if you want to add a new dependency to this plugin, just open a PR updating this file: https://github.com/mastilver/module-to-cdn/blob/master/modules.json and it will work the next time you update

I agree it's a bit ugly atm (I will try to simplify that in the future), but at least it's 100% reliable :)
